/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"



int main(void)
{
	RCC_AHB2ENR_t *pRCC_AHB2ENR = (RCC_AHB2ENR_t*)0x46020C00;
	GPIOx_MODER_t *pGPIOB_MODER = (GPIOx_MODER_t*)0x42020400;
	GPIOx_ODR_t *pGPIOB_ODR     = (GPIOx_ODR_t*)0x42020414;

	pRCC_AHB2ENR->gpiob_en = 1;
	pGPIOB_MODER->pin_7=1;
	//pGPIOD_MODER->pin_13=1;


	for(;;){
		pGPIOB_ODR->pin_7=1;
		//pGPIOD_ODR->pin_13=1;
		for(uint32_t i = 0;i<1000000;i++);
		pGPIOB_ODR->pin_7=0;
		//pGPIOD_ODR->pin_13=0;
		for(uint32_t i = 0;i<1000000;i++);
	}
}
