/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *pRCC =(uint32_t*) 0x40023830;
    uint32_t *pGPIOA_MODEDR = (uint32_t*)0x40020000;
    uint32_t *pGPIOA_OUTDR = (uint32_t*)0x40020014;

    //1. Enable the clock for gpioa peripheral :
    *pRCC |= (1<<0);

    //2. Configue the mode of GPIOA (OUTPUT)
    *pGPIOA_MODEDR &= ~((1<<10)+(1<<11));
    *pGPIOA_MODEDR |= (1<<10);

    //3. Write the value in Data reg of GPIOA :

    *pGPIOA_OUTDR &= ~(1<<5);
    *pGPIOA_OUTDR |= (1<<5);

    while(1);



}
