/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *const volatile pRCC = (uint32_t *) 0x40023830;
	uint32_t *const volatile pGPIOA_DR = (uint32_t *) 0x40020000;
	uint32_t *const volatile pGPIOA_ODR = (uint32_t *) 0x40020014;
	uint32_t *const volatile pGPIOA_PUPDR = (uint32_t *) 0x4002000C;
	uint32_t const *const volatile pGPIOA_IDR = (uint32_t *) 0x40020010;
	uint32_t temp;

	*pRCC |= (1<<0); ///Enable GPIOA

	*pGPIOA_DR &= ~(3<<0); //PA0 Input
	*pGPIOA_DR |= (1<<10); //PA5 Output

	*pGPIOA_PUPDR |= (1<<1); //PA0 is set to pull down;

	for(;;){
		temp = *pGPIOA_IDR;
		if(temp &= (1<<0)){
			*pGPIOA_ODR |= (1<<5);
		}
		else
			*pGPIOA_ODR &= ~(1<<5);
	}

}
